### ISSUE TITLE
Error while installing Flutter

### ISSUE THREAD

**Issue by kodeaqua** [fahminlb33/KFlearning#10]
After downloading Flutter, an error occurred while installing Flutter

Logs:
https://pastebin.com/ziPrW40j

Screenshot:
![1](https://user-images.githubusercontent.com/33061778/152626949-ff27415e-4ebf-42ef-8fd0-eb565f6d744d.png)

P.S: 
Another bug is, when user doesn't have KFMinGW, the program will bypass to main activity. But if user doesn't have Visual Studio Code, the program will force closed.

Thanks :d

**Comment by fahminlb33** [comment]
For the second behavior it is expected because I purposefully disabled it

**Comment by fahminlb33** [comment]
The proposed solution is in https://github.com/fahminlb33/KFlearning/commit/bfb544368c3ced09f8c5ce641afd09bd2cbc412d
