### ISSUE TITLE
Tidak bisa mendeteksi visual studio code yang diinstall di Program Files

### ISSUE THREAD

**Issue by rasyidf** [fahminlb33/KFlearning#3]
saat memulai menjalankan program, aplikasi tidak mendeteksi adanya visual studio code.
padahal vs code sudah terinstall dan berjalan normal.

**Tingkah Laku yang diharapkan:**
Aplikasi mendeteksi lokasi vscode untuk setiap kondisi

**Tingkah laku yang terjadi:**
Aplikasi tidak mendeteksi lokasi vscode untuk mode sistem (diinstall di ProgramFiles)

**Solusi**
Tambahkan fitur kustom path.

**Comment by fahminlb33** [comment]
Siap, saat ini pendeteksian Visual Studio Code hanya untuk User Install dan tidak mendeteksi System-wide Install. Pertimbangan ini karena target pengguna KFlearning ini adalah mahasiswa awam pemrograman dan untuk di laboratorium komputer, maka awalnya jenis instalasi VSCode dibatasi khusus untuk user install.

Apa pertimbangan untuk mengimplementasikan fitur ini?

*biasa aja ya chat nya :v ini lagi mode community jadi bahasanya tinggi 😄

**Comment by rasyidf** [comment]
Terkadang visual studio di install di lokasi berbeda karena alasan tertentu (portabilitas, maupun batasan kapasitas drive utama)  karena itu memberi pilihan kepada pengguna akan lebih masuk akal dibandingkan dengan hardcoded data.

**Comment by fahminlb33** [comment]
OK, ada saran gimana buat sistem pendeteksian ini? Apa di limit hanya aplikasi yang mencari lokasi instalasi VSCode atau disediakan di bagian settings untuk memilih lokasi VSCode?

**Comment by rasyidf** [comment]
kita bisa mendeteksi luaran dari pemanggilan `code.exe -v`  kemudian menentukan lokasi berdasar pada environment variables

**Comment by fahminlb33** [comment]
Resolved in https://github.com/fahminlb33/KFlearning/commit/eadb2ce06087b78c8635bd7e66b72f7b4c6467ea
