### ISSUE TITLE
Scaling Dpi belum diimplementasikan  

### ISSUE THREAD

**Issue by rasyidf** [fahminlb33/KFlearning#4]
untuk layar besar, aplikasi terlihat sangat kecil. meskipun sudah di pasang DPI lebih.

**Comment by fahminlb33** [comment]
Untuk scaling ini selain dari Winform Designer, tolong ditambahkan juga dari app.manifest.
https://docs.microsoft.com/en-us/previous-versions/windows/desktop/legacy/mt846517(v%3Dvs.85)

**Comment by rasyidf** [comment]
Penambahan manifest tidak akan berpengaruh di windows 7
apakah support nya masih dipertahankan?
