### ISSUE TITLE
Inkonsistensi Margin dan tema.

### ISSUE THREAD

**Issue by rasyidf** [fahminlb33/KFlearning#5]
meskipun sebuah issue kecil, namun penempatan kontrol tanpa memerhatikan konsistensi akan mengurangi daya tarik.

**Comment by rasyidf** [comment]
Saran Margin:
Major : 28
Minor : 20

**Comment by fahminlb33** [comment]
Baik

**Comment by fahminlb33** [comment]
Solved in https://github.com/fahminlb33/KFlearning/pull/6
