### ISSUE TITLE
"Install Flutter" feature isn't working

### ISSUE THREAD

**Issue by kodeaqua** [fahminlb33/KFlearning#7]
Because the URL was changed.
from:
https://storage.googleapis.com/flutter_infra/releases/stable/windows/flutter_windows_{version}-stable.zip
to:
https://storage.googleapis.com/flutter_infra_release/releases/stable/windows/flutter_windows_{version}-stable.zip

FlutterGitClient.cs
![Screenshot (17)](https://user-images.githubusercontent.com/33061778/132939123-76c8b505-eaed-4215-9790-af34e98fb423.png)

**Comment by fahminlb33** [comment]
Thank you! I'll fix this issue in the next canary version before the campus begins.
You also can submit a PR to fix this issue by yourself! It's always nice to get someone to contribute to this project.
