### ISSUE TITLE
Tambahkan opsi untuk executable path dan include path

### ISSUE THREAD

**Issue by rasyidf** [fahminlb33/KFlearning#8]
Agar dapat memberikan admin dan user kemudahan, tambahkan pengaturan untuk secara manual mengelola include path, maupun path untuk visual studio code, dan mingw

**Comment by fahminlb33** [comment]
Untuk saat ini includePath sudah diset hanya untuk workspace dan MinGW karena target KFlearning ini hanya untuk beginner, tidak perlu bisa include yang selain bawaan (STL). Kalau memang sudah advanced, tidak perlu menggunakan template KFlearning.

Menurut saya fitur ini terlalu overkill untuk target audience.
